


apply plugin: 'eclipse'

eclipse {
    project {
        name = "Dynmap(DynmapCoreAPI)"
    }
}

description = "DynmapCoreAPI"
version = project.version
group = project.group

base {
	archivesName = project.name
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

jar {
    destinationDirectory = file '../target'
}

artifacts {
    archives jar
}
// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}