plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

eclipse {
    project {
        name = "Dynmap(Fabric-26.1)"
    }
}


version = parent.version
group = parent.group

base {
	archivesName = project.archives_base_name
}

configurations {
    shadow
    implementation.extendsFrom(shadow)
}

repositories {
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
	maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    mavenCentral()
    gradlePluginPortal()
}

loom {
	// accessWidenerPath = file("src/main/resources/dynmap.accesswidener")
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    // mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    compileOnly group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.2'

    shadow project(path: ':DynmapCore', configuration: 'shadow')
	
    compileOnly "me.lucko:fabric-permissions-api:0.6.0"
    compileOnly 'net.luckperms:api:5.5'
}

processResources {
    filesMatching('fabric.mod.json') {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
	
}

tasks.shadowJar {
    zip64 = true
	    dependencies {
        include(dependency(':DynmapCore'))
    }
	relocate('org.dynmap', 'org.dynmap.fabric_26_1')
    destinationDirectory = file('../target')
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
    archiveFileName = "${base.archivesName.get()}-${project.version}-fabric-${project.minecraft_version}.jar"
    destinationDirectory = file('../target')
    inputs.property "archivesName", base.archivesName.get()
    from "LICENSE"
    from {
        configurations.shadow.collect { it.toString().contains("guava") ? null : it.isDirectory() ? it : zipTree(it) }
    }
	doLast {
		def jarFile = archiveFile.get().asFile
		def checksum = org.apache.commons.codec.digest.DigestUtils.sha256Hex(jarFile.newInputStream())
		def checksumFile = new File(jarFile.parentFile, jarFile.name + ".sha256")
		checksumFile.text = checksum
	}
}


// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}